//! Generates a directory tree with known duplicates, for trying dupefind out.
//!
//! ```sh
//! cargo run --example make-testdata            # creates ./testdata
//! cargo run --example make-testdata -- /tmp/x  # somewhere else
//! ```
//!
//! Testing dupefind means deleting files, so this is a generator rather than
//! committed fixtures: re-run it to get the tree back. It prints the result the
//! scan should produce, computed from the same table it writes, so the stated
//! expectation cannot drift from what is on disk.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// A set of paths that should all end up holding identical content.
struct Group {
    /// Bytes per copy.
    size: usize,
    /// Distinguishes one group's content from another's.
    seed: u64,
    paths: &'static [&'static str],
}

/// Groups the scan is expected to report with the default filters.
const GROUPS: &[Group] = &[
    Group {
        size: 1_500_000,
        seed: 1,
        paths: &[
            "photos/2019/vacation.jpg",
            "downloads/vacation.jpg",
            "backup/2019/vacation.jpg",
        ],
    },
    Group {
        size: 800_000,
        seed: 2,
        paths: &["music/song.flac", "backup/music/song.flac"],
    },
    // Four copies of a library that several applications legitimately ship.
    // Deleting these blindly is exactly what group selection is for: mark the
    // group and skip it, or pick only the copies you really want gone.
    Group {
        size: 250_000,
        seed: 3,
        paths: &[
            "apps/alpha/shared.dll",
            "apps/beta/shared.dll",
            "apps/gamma/shared.dll",
            "system/shared.dll",
        ],
    },
    Group {
        size: 120_000,
        seed: 4,
        paths: &["docs/report.pdf", "docs/archive/report.pdf"],
    },
];

/// Marker so the generator will only ever clear a tree it made itself.
const MARKER: &str = ".dupefind-testdata";

fn main() -> io::Result<()> {
    let root = PathBuf::from(
        std::env::args()
            .nth(1)
            .unwrap_or_else(|| "testdata".to_string()),
    );

    if root.exists() {
        if !root.join(MARKER).exists() {
            eprintln!(
                "{} already exists and was not created by this generator.\n\
                 Refusing to touch it. Remove it yourself, or pass another path.",
                root.display()
            );
            std::process::exit(1);
        }
        fs::remove_dir_all(&root)?;
    }
    fs::create_dir_all(&root)?;
    fs::write(
        root.join(MARKER),
        b"generated by cargo run --example make-testdata\n",
    )?;

    for group in GROUPS {
        let content = filler(group.seed, group.size);
        for path in group.paths {
            write_file(&root, path, &content)?;
        }
    }

    // --- files that must NOT be reported, each covering a different rule ---

    // Unique content, and two different sizes so size-bucketing drops them.
    write_file(&root, "unique/notes.txt", &filler(10, 40_000))?;
    write_file(&root, "unique/other.txt", &filler(11, 40_001))?;

    // Identical size, different content: proves matching is by content, not size.
    write_file(&root, "tricky/same-size-a.bin", &filler(20, 64_000))?;
    write_file(&root, "tricky/same-size-b.bin", &filler(21, 64_000))?;

    // Same size and same first 100 KiB, differing only in the final byte. The
    // head-hash phase cannot separate these; only the full hash can.
    let mut head_a = filler(30, 200_000);
    let mut head_b = head_a.clone();
    *head_a.last_mut().expect("non-empty") = 0x01;
    *head_b.last_mut().expect("non-empty") = 0x02;
    write_file(&root, "tricky/same-head-a.bin", &head_a)?;
    write_file(&root, "tricky/same-head-b.bin", &head_b)?;

    // Empty files are all identical; excluded unless --include-empty.
    write_file(&root, "empty/one.txt", b"")?;
    write_file(&root, "empty/two.txt", b"")?;

    // Hidden copy of group 1; excluded unless --hidden.
    write_file(&root, ".hidden-vacation.jpg", &filler(1, 1_500_000))?;

    // Gitignored copy of group 1; excluded unless --no-gitignore.
    write_file(&root, ".gitignore", b"build/\n")?;
    write_file(&root, "build/ignored-vacation.jpg", &filler(1, 1_500_000))?;

    let hardlinked = make_hardlink(&root)?;

    report(&root, hardlinked);
    Ok(())
}

/// Two names for one inode. Collapsed by default, since deleting one frees
/// nothing; `--no-collapse-hardlinks` reports them as a pair.
#[cfg(unix)]
fn make_hardlink(root: &Path) -> io::Result<bool> {
    let original = root.join("links/original.bin");
    write_file(root, "links/original.bin", &filler(40, 90_000))?;
    fs::hard_link(&original, root.join("links/hardlink.bin"))?;
    Ok(true)
}

#[cfg(not(unix))]
fn make_hardlink(root: &Path) -> io::Result<bool> {
    // std::fs::hard_link works on Windows too, but only within one volume and
    // on NTFS, so a failure here is not worth aborting the whole fixture for.
    let original = root.join("links/original.bin");
    write_file(root, "links/original.bin", &filler(40, 90_000))?;
    Ok(fs::hard_link(&original, root.join("links/hardlink.bin")).is_ok())
}

fn write_file(root: &Path, relative: &str, bytes: &[u8]) -> io::Result<()> {
    let path = root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, bytes)
}

/// Deterministic pseudo-random bytes, so re-running produces the same hashes.
fn filler(seed: u64, len: usize) -> Vec<u8> {
    let mut state = seed.wrapping_mul(0x9E37_79B9_7F4A_7C15).wrapping_add(1);
    (0..len)
        .map(|_| {
            // A plain LCG: enough to defeat compression, no dependency needed.
            state = state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            (state >> 33) as u8
        })
        .collect()
}

/// State the expected outcome, derived from GROUPS so it stays truthful.
fn report(root: &Path, hardlinked: bool) {
    let groups = GROUPS.len();
    let duplicates: usize = GROUPS.iter().map(|g| g.paths.len() - 1).sum();
    let reclaimable: usize = GROUPS.iter().map(|g| g.size * (g.paths.len() - 1)).sum();

    println!("Created {}\n", root.display());
    println!("A default scan should report:");
    println!("  groups       {groups}");
    println!("  duplicates   {duplicates}");
    println!(
        "  reclaims     {:.2} MiB ({reclaimable} bytes)",
        reclaimable as f64 / (1024.0 * 1024.0)
    );
    println!("\nGroups, largest waste first:");
    let mut sorted: Vec<&Group> = GROUPS.iter().collect();
    sorted.sort_by_key(|g| std::cmp::Reverse(g.size * (g.paths.len() - 1)));
    for g in sorted {
        let name = g.paths[0].rsplit('/').next().unwrap_or(g.paths[0]);
        println!(
            "  {name:<14} x{}  {} KiB each",
            g.paths.len(),
            g.size / 1024
        );
    }

    println!("\nDeliberately NOT reported, and why:");
    println!("  unique/*             unique content, and two different sizes");
    println!("  tricky/same-size-*   equal size, different content");
    println!("  tricky/same-head-*   equal first 100 KiB, differ in the last byte");
    println!("  empty/*              0-byte files      (see --include-empty)");
    println!("  .hidden-vacation.jpg hidden            (see --hidden)");
    println!("  build/*              gitignored        (see --no-gitignore)");
    if hardlinked {
        println!("  links/*              one inode, two names (--no-collapse-hardlinks)");
    }

    println!("\nTry it:");
    println!("  cargo run --release -- {}", root.display());
    println!("\nThe shared.dll group has 4 copies across apps/ and system/ -- a");
    println!("library several applications need. Use it to try group selection:");
    println!("  m marks a group, Shift+up/down extends a block, x skips them.");
}
